version: '3'
services:
  web:
    build: .
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./data/certbot/www:/var/www/certbot
      - ./data/letsencrypt:/etc/letsencrypt
  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/www:/var/www/certbot
      - ./data/letsencrypt:/etc/letsencrypt
    entrypoint: ''
    command: >
      certonly --webroot --webroot-path=/var/www/certbot \
      --email jpfurlan@hotmail.com.br --agree-tos --no-eff-email \
      -d jpfurlan.dev -d www.jpfurlan.dev
