version: '3.8'

services:
  web:
    image: port-web # ou build: . se quiser rebuildar local
    expose:
      - '80'
    environment:
      VIRTUAL_HOST: jpfurlan.dev,www.jpfurlan.dev
      LETSENCRYPT_HOST: jpfurlan.dev,www.jpfurlan.dev
      LETSENCRYPT_EMAIL: jpfurlan@hotmail.com.br
    networks:
      - proxy

networks:
  proxy:
    external: true
